version: '3.1'

services:
  mysql:
    platform: linux/arm64/v8
    image: 'arm64v8/mysql'
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin

